#!/usr/bin/env python3
"""
execute_magnet_path.py  –  Auto-execute a magnet trajectory on the Franka FR3

This ROS node loads a trajectory file (5×N or 6×N) generated by
generate_magnet_path.py and drives the arm through all waypoints.

Execution strategy:
  1. PRIMARY: MoveIt compute_cartesian_path() — plans the entire trajectory
     (or chunks) as a smooth Cartesian path in one shot.
  2. FALLBACK: If Cartesian planning fails (fraction < threshold), falls back
     to point-by-point MoveIt plan() + execute() for the remaining waypoints.

Modes:
  --mode auto     :  Executes all waypoints automatically with a configurable
                     delay between points (default).
  --mode manual   :  Waits for the user to press Enter before each step.
  --mode joystick :  Waits for joystick B button (same as original tracking).

Usage:
  rosrun <pkg> execute_magnet_path.py --config config.json --trajectory magnet_path.txt --mode auto

Dependencies:
  Same as franka_magnet_controller.py  +  the trajectory .txt files.

Author: (generated with assistance from Claude)
"""

import sys
import os
import json
import argparse
import time

import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from geometry_msgs.msg import Pose
from sensor_msgs.msg import Joy
from std_msgs.msg import Bool, Float64MultiArray

import tf.transformations as ttf
from tf.transformations import quaternion_from_euler, euler_from_quaternion
import numpy as np
from math import radians, degrees, pi


# ---------------------------------------------------------------------------
#  link_back_L  (self-contained copy)
# ---------------------------------------------------------------------------

def link_back_L(end_x, end_y, end_z, end_roll, end_pitch, end_yaw,
                end_effector_height, end_effector_length):
    """Convert magnet-tip pose → panda_link8 pose (L-shaped bracket)."""
    p_end = np.mat([end_x, end_y, end_z, 1.0]).T
    p_local = np.mat([0, end_effector_length, end_effector_height, 1.0]).T
    link_roll, link_yaw, link_pitch = end_roll, end_pitch, end_yaw
    quaternion = ttf.quaternion_from_euler(link_roll, link_pitch, link_yaw, 'rxyz')
    Rq = np.mat(ttf.quaternion_matrix(quaternion))
    p_link = p_end - Rq @ p_local
    link_x, link_y, link_z = np.array(p_link).reshape(-1)[:3]
    return [link_x, link_y, link_z, link_roll, link_pitch, link_yaw]


def link_forward_L(link_x, link_y, link_z, link_roll, link_pitch, link_yaw,
                   end_effector_height, end_effector_length):
    """Inverse of link_back_L: panda_link8 pose → magnet-tip pose."""
    p_link = np.mat([link_x, link_y, link_z, 1.0]).T
    p_local = np.mat([0, end_effector_length, end_effector_height, 1.0]).T
    quaternion = ttf.quaternion_from_euler(link_roll, link_pitch, link_yaw, 'rxyz')
    Rq = np.mat(ttf.quaternion_matrix(quaternion))
    p_end = p_link + Rq @ p_local
    end_x, end_y, end_z = np.array(p_end).reshape(-1)[:3]
    end_roll  = link_roll
    end_pitch = link_yaw
    end_yaw   = link_pitch
    return [end_x, end_y, end_z, end_roll, end_pitch, end_yaw]


def get_link8_euler(group):
    """Read current panda_link8 pose → (x, y, z, roll, pitch, yaw)."""
    pose = group.get_current_pose().pose
    q = [pose.orientation.x, pose.orientation.y,
         pose.orientation.z, pose.orientation.w]
    roll, pitch, yaw = euler_from_quaternion(q, axes='rxyz')
    return (pose.position.x, pose.position.y, pose.position.z,
            roll, pitch, yaw)


# ---------------------------------------------------------------------------
#  Config loader
# ---------------------------------------------------------------------------

def load_config(path):
    with open(path, 'r') as f:
        return json.load(f)


# ===========================================================================
#  TrajectoryExecutor
# ===========================================================================

class TrajectoryExecutor:
    """Load a trajectory and execute it on the Franka FR3."""

    def __init__(self, cfg, traj_file, arg, joint_init, mode='auto',
                 cartesian_fraction_thresh=0.90, point_delay=0.1):
        self.cfg = cfg
        self.mode = mode
        self.cartesian_thresh = cartesian_fraction_thresh
        self.point_delay = point_delay
        self.arg = arg
        motor_cfg = cfg["motor"]
        self.joint_init = joint_init 
        from utils.arduino_control import Stepper_servo
        self.stepper = Stepper_servo(
            serial_no=motor_cfg["serial_no"],
            servo_vel_step=motor_cfg["step_rotation"])
        self.stepper.servo_stop()
        if arg.b_enable_motor:
            self.stepper.servo_rotate(1000)
        else:
            self.stepper.servo_stop()

        # --- Config ---
        robot_cfg = cfg["robot"]
        ee_cfg    = cfg["end_effector"]
        magnet_key = ee_cfg["magnet_key"]
        mag_set = ee_cfg["magnet_settings"][magnet_key]

        self.ee_height = ee_cfg["end_effector_height_mm"] * 1e-3
        self.ee_length = mag_set["end_effector_length_mm"] * 1e-3
        self.arm_acc   = robot_cfg["arm_acc"]

        self.thresh_singular = robot_cfg["singularity_thresholds"]
        self.planning_repeat = robot_cfg["planning_repeat"]

        # --- Load trajectory (6×N preferred, 5×N backwards-compatible) ---
        raw = np.loadtxt(traj_file)
        if raw.ndim == 1:
            raw = raw.reshape(-1, 1)
        if raw.shape[0] == 6:
            self.traj = raw[:5, :].T          # shape (N, 5): x,y,z,alpha,phi
            self.yaw_offsets = raw[5, :]       # shape (N,)
            print("Loaded 6×N trajectory: %s  (%d waypoints, yaw included)",
                          traj_file, self.traj.shape[0])
        elif raw.shape[0] == 5:
            self.traj = raw.T
            self.yaw_offsets = np.zeros(self.traj.shape[0])
            print("Loaded 5×N trajectory: %s  (%d waypoints, yaw=0)",
                          traj_file, self.traj.shape[0])
        else:
            raise ValueError(f"Trajectory shape {raw.shape} not recognised (expected 6×N or 5×N)")

        # --- ROS / MoveIt ---
        rospy.init_node('trajectory_executor', anonymous=True)
        moveit_commander.roscpp_initialize(sys.argv)

        self.robot = moveit_commander.RobotCommander()
        self.scene = moveit_commander.PlanningSceneInterface()
        self.group = moveit_commander.MoveGroupCommander(robot_cfg["group_name"])

        vel = mag_set.get("vel", robot_cfg.get("vel_scale", 0.05))
        acc = mag_set.get("acc", robot_cfg.get("acc_scale", 0.05))
        self.group.set_max_velocity_scaling_factor(vel)
        self.group.set_max_acceleration_scaling_factor(acc)

        print("Planning frame: %s", self.group.get_planning_frame())
        print("End effector  : %s", self.group.get_end_effector_link())

        # --- Joystick (for manual/joystick mode) ---
        self.joy_proceed = False
        if mode == 'joystick':
            self.joy_sub = rospy.Subscriber("joy", Joy, self._joy_cb, queue_size=10)

        # --- Optional: go to joints_init ---
        rate1 = rospy.Rate(1)
        
        if robot_cfg.get("use_joints_init", False):
            joints = robot_cfg.get("joints_init", [])
            if joints:
                print("Moving to joints_init...")
                self.group.go(joints, wait=True)
                rate1.sleep()
        # go to joint init
        if self.arg.b_enable_joint_init:
            joints = self.joint_init
            self.group.go(joints, wait=True)
            rospy.sleep(0.5)
        else:
            print(self.group.get_current_joint_values())

        # --- Capture current pose as base ---
        print("="*60)
        print("  Please move the arm to the desired starting pose.")
        print("  Press ENTER to capture and begin trajectory execution.")
        print("="*60)
        input(">>> Press ENTER... ")

        lx, ly, lz, lr, lp, lyw = get_link8_euler(self.group)
        mag = link_forward_L(lx, ly, lz, lr, lp, lyw, self.ee_height, self.ee_length)
        self.base_pose = np.array(mag)
        self.joints_at_init = self.group.get_current_joint_values()

        print("Base magnet pose: xyz=(%.4f, %.4f, %.4f)  rpy=(%.1f, %.1f, %.1f) deg",
                      mag[0], mag[1], mag[2], degrees(mag[3]), degrees(mag[4]), degrees(mag[5]))

    # ------------------------------------------------------------------
    # Joystick callback
    # ------------------------------------------------------------------

    def _joy_cb(self, msg):
        """In joystick mode, pressing B advances to the next waypoint."""
        if msg.buttons[2] == 1:  # B button
            self.joy_proceed = True

    # ------------------------------------------------------------------
    # Build link8 Pose message from magnet-tip coordinates
    # ------------------------------------------------------------------

    def _magnet_to_pose_msg(self, mx, my, mz, mroll, mpitch, myaw):
        """Convert absolute magnet-tip pose → geometry_msgs/Pose for link8."""
        lp = link_back_L(mx, my, mz, mroll, mpitch, myaw,
                         self.ee_height, self.ee_length)
        pose = Pose()
        pose.position.x = np.round(lp[0] / self.arm_acc, 0) * self.arm_acc
        pose.position.y = np.round(lp[1] / self.arm_acc, 0) * self.arm_acc
        pose.position.z = np.round(lp[2] / self.arm_acc, 0) * self.arm_acc
        q = quaternion_from_euler(lp[3], lp[4], lp[5], 'rxyz')
        pose.orientation.x = q[0]
        pose.orientation.y = q[1]
        pose.orientation.z = q[2]
        pose.orientation.w = q[3]
        return pose

    # ------------------------------------------------------------------
    # Planning helpers
    # ------------------------------------------------------------------

    def _plan_and_execute_single(self, pose_msg):
        """Plan + execute a single pose target with singularity detection."""
        group = self.group
        group.clear_path_constraints()
        group.set_pose_target(pose_msg)
        flag, traj, _, _ = group.plan()

        # Check joint jump
        jc = np.array(group.get_current_joint_values())
        jn = np.array(traj.joint_trajectory.points[-1].positions)
        err = np.sum(np.abs(jc - jn)[:-1])

        if err > self.thresh_singular[0]:
            rospy.logwarn("Singularity (err=%.2f) — replanning...", err)
            for thresh, rep in zip(self.thresh_singular, self.planning_repeat):
                trajects, errors = [], []
                for _ in range(rep):
                    group.set_pose_target(pose_msg)
                    _, t, _, _ = group.plan()
                    jn2 = np.array(t.joint_trajectory.points[-1].positions)
                    e = np.sum(np.abs(jc - jn2)[:-1])
                    trajects.append(t)
                    errors.append(e)
                best = int(np.argmin(errors))
                if errors[best] < thresh:
                    traj = trajects[best]
                    print("Replan OK (err=%.2f < %.2f)", errors[best], thresh)
                    break
            else:
                rospy.logwarn("All replans exceeded thresholds — executing best available")
                best = int(np.argmin(errors))
                traj = trajects[best]

        group.execute(traj, wait=True)

    # ------------------------------------------------------------------
    # Execute trajectory
    # ------------------------------------------------------------------

    def execute(self):
        """Main execution loop."""
        N = self.traj.shape[0]
        bp = self.base_pose



        # Build list of absolute link8 Pose messages for Cartesian planning
        print("Building waypoint list (%d points)...", N)
        pose_msgs = []
        for i in range(N):
            mx = bp[0] + self.traj[i, 0]
            my = bp[1] + self.traj[i, 1]
            mz = bp[2] + self.traj[i, 2]
            mr = bp[3] + self.traj[i, 3]
            mp = bp[4] + self.traj[i, 4]
            myaw = bp[5] + self.yaw_offsets[i]
            pose_msgs.append(self._magnet_to_pose_msg(mx, my, mz, mr, mp, myaw))

        # === Strategy A: Cartesian path ===
        if self.mode == 'auto':
            print("Attempting Cartesian path planning for all %d waypoints...", N)
            cartesian_ok = False#self._try_cartesian(pose_msgs)
            if cartesian_ok:
                print("Cartesian execution complete!")
                return
            else:
                rospy.logwarn("Cartesian planning failed — falling back to point-by-point.")

        # === Strategy B: Point-by-point ===
        print("Executing point-by-point (%s mode)...", self.mode)
        for i in range(N):
            # Wait for user input depending on mode
            if self.mode == 'manual':
                input(f"  [{i+1}/{N}] Press ENTER to proceed...")
            elif self.mode == 'joystick':
                print("  [%d/%d] Press B on joystick to proceed...", i+1, N)
                self.joy_proceed = False
                while not self.joy_proceed and not rospy.is_shutdown():
                    rospy.sleep(0.05)

            t0 = time.time()
            self._plan_and_execute_single(pose_msgs[i])
            dt = time.time() - t0

            mx = bp[0] + self.traj[i, 0]
            my = bp[1] + self.traj[i, 1]
            mz = bp[2] + self.traj[i, 2]
            print("  [%d/%d] xyz=(%.3f,%.3f,%.3f) | %.2f s",
                          i+1, N, mx, my, mz, dt)

            if self.mode == 'auto' and self.point_delay > 0:
                rospy.sleep(self.point_delay)
        self.group.go(self.joints_at_init, wait=True)
        print("Trajectory execution complete!")
        self.stepper.servo_stop()

    def _try_cartesian(self, pose_msgs, chunk_size=50, eef_step=0.002, jump_thresh=0.0):
        """Try to execute via compute_cartesian_path in chunks.

        Parameters
        ----------
        pose_msgs : list of Pose
        chunk_size : int
            Number of waypoints per Cartesian plan attempt.
        eef_step : float
            Max step between interpolated points (m).
        jump_thresh : float
            Max allowed joint jump (0 = disabled).

        Returns
        -------
        bool : True if the entire trajectory was executed.
        """
        group = self.group
        N = len(pose_msgs)
        idx = 0

        while idx < N:
            chunk_end = min(idx + chunk_size, N)
            waypoints = pose_msgs[idx:chunk_end]

            print("  Cartesian chunk [%d..%d] / %d ...", idx+1, chunk_end, N)
            trajectory, fraction = group.compute_cartesian_path(
                waypoints, eef_step, jump_thresh)

            print("    fraction = %.2f%%", fraction * 100)

            if fraction < self.cartesian_thresh:
                rospy.logwarn("    Cartesian fraction %.2f%% < threshold %.0f%% — aborting Cartesian.",
                              fraction * 100, self.cartesian_thresh * 100)
                return False

            # Execute the planned trajectory
            group.execute(trajectory, wait=True)
            idx = chunk_end

        return True


# ===========================================================================
#  Entry point
# ===========================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Execute a magnet trajectory on the Franka FR3",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('--config', type=str, default='/home/roboticarm/catkin_ws/src/arm_control_magnet/src/config.json',
                        help='Path to JSON config file')
    parser.add_argument('--trajectory', type=str, default='/home/roboticarm/catkin_ws/src/arm_control_magnet/src/path_random/magnet_path_tiny.txt',
                        help='Path to trajectory .txt file (5×N or 6×N)')
    parser.add_argument('--mode', type=str, default='auto',
                        choices=['auto', 'manual', 'joystick'],
                        help='Execution mode')
    parser.add_argument('--cartesian_thresh', type=float, default=0,
                        help='Minimum fraction for Cartesian path to be accepted')
    parser.add_argument('--chunk_size', type=int, default=50,
                        help='Number of waypoints per Cartesian planning chunk')
    parser.add_argument('--delay', type=float, default=0.1,
                        help='Delay between points in auto point-by-point mode (s)')
    parser.add_argument('--b_enable_motor', type=bool, default=True,
                        help='if let the motor rotate')
    parser.add_argument('--b_enable_joint_init', type=bool, default=False,
                        help='if let the arm go to the initial joint first')
    joint_init = [-0.08407313944274282, 0.0484994226192087, -0.20808485028247958, -1.9070227053507809, -0.0391489009840427, 1.9458937111271293, -0.2222129636284362]

    args = parser.parse_args(rospy.myargv()[1:])

    cfg = load_config(args.config)



    try:
        executor = TrajectoryExecutor(
            cfg, args.trajectory, args, joint_init,
            mode=args.mode,
            cartesian_fraction_thresh=args.cartesian_thresh,
            point_delay=args.delay)
        executor.execute()
    except rospy.ROSInterruptException:
        executor.stepper.servo_stop()
        pass


if __name__ == '__main__':
    main()
